mixed-port: 7890
redir-port: 9797
tproxy-port: 9898
ipv6: false
mode: Rule
allow-lan: false
unified-delay: true
tcp-concurrent: true
log-level: silent
bind-address: "*"
find-process-mode: strict
external-controller: 0.0.0.0:9090
external-ui-url: "https://v6.gh-proxy.org/https://github.com/Zephyruso/zashboard/releases/latest/download/dist-no-fonts.zip"
external-ui: "dashboard"
secret: ""

p: &p
  type: http
  interval: 86400
  health-check:
    enable: true
    url: 'https://www.gstatic.com/generate_204'
    interval: 3600
    timeout: 5000
  proxy: SUB
  exclude-filter: '(?i)官网|邀请|到期|更新|验证|剩余|频道|长期|推广|分享|周期|我的'
  header:
      User-Agent:
      - "ClashMetaForAndroid/v2.11.26"

proxy-providers:
  sm:
    <<: *p
    path: ./proxy_provider/sm.yaml
    url: ""
    
  lx:
    <<: *p
    path: ./proxy_provider/lx.yaml
    url: ""

  cx:
    <<: *p
    path: ./proxy_provider/cx.yaml
    url: ""

  zj:
    <<: *p
    path: ./proxy_provider/zj.yaml
    url: ""

profile:
  store-selected: true
  store-fake-ip: true

ntp:
  enable: true
  write-to-system: false
  server: ntp.ntsc.ac.cn
  port: 123
  interval: 60

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 5228, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "Mijia Cloud" 

tun:
  enable: false
  device: meta
  stack: mixed
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  strict-route: false
  auto-detect-interface: true
  route-exclude-address:
  - 127.0.0.1/8
  - ::1/128
  - fe80::/10
  - 192.168.0.0/16

dns:
  enable: true
  ipv6: false
  cache-algorithm: arc
  prefer-h3: false
  use-hosts: true
  use-system-hosts: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::1/64
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - RULE-SET,CN_域
    - RULE-SET,Fake-IP-Filter
    - RULE-SET,Private_域
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver-policy:
    "RULE-SET:CN_域":
      - 223.5.5.5
      - 119.29.29.29
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query
  nameserver:
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
  direct-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  direct-nameserver-follow-policy: true

pr: &pr
    type: select
    proxies: [Proxy,HK,SG,JP,TW,ZJ,ALL,DIRECT]

proxy-groups:
  - {name: Proxy, type: select, proxies: [HK, SG, JP, TW, ZJ, ALL, DIRECT]}
  - {name: SUB, type: select, proxies: [DIRECT, Proxy]}
  - {name: AI, <<: *pr}
  - {name: TG, <<: *pr}
  - {name: HK, type: select, use: [sm, lx, cx], filter: "^(?=.*(港|HK|hk|Hong Kong|HongKong|hongkong)).*$"}
  - {name: SG, type: select, use: [sm, lx, cx], filter: "^(?=.*(新加坡|坡|狮城|SG|Singapore)).*$"}
  - {name: JP, type: select, use: [sm, lx, cx], filter: "^(?=.*(日|日本|JP|Japan)).*$"}
  - {name: TW, type: select, use: [sm, lx, cx], filter: "^(?=.*(台|TW|Taiwan)).*$"}
  - {name: ZJ, type: select, use: [zj]}
  - {name: ALL, type: select, use: [sm, lx, cx, zj]}
  - {name: Final, <<: *pr}

rule-anchor:
  Class: &Class {type: http, behavior: classical, format: text, interval: 86400}
  IPCIDR: &IPCIDR {type: http, behavior: ipcidr, format: mrs, interval: 86400}
  Domain: &Domain {type: http, behavior: domain, format: mrs, interval: 86400}

rule-providers:
  Directlist:
    <<: *Class
    path: ./rules/Directlist.list
    url: "https://v6.gh-proxy.org/https://github.com/xiongtee/mihomo/raw/refs/heads/main/rules/direct.list"
  Applications:
    <<: *Class
    path: ./rules/Applications.list
    url: "https://v6.gh-proxy.org/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/applications.list"
  Fake-IP-Filter:
    <<: *Domain
    path: ./rules/Fake-IP-Filter.mrs
    url: "https://v6.gh-proxy.org/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/fakeip-filter.mrs"
  CN_IP:
    <<: *IPCIDR
    path: ./rules/CN_IP.mrs
    url: "https://v6.gh-proxy.org/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/cnip.mrs"
  CN_域:
    <<: *Domain
    path: ./rules/CN_域.mrs
    url: "https://v6.gh-proxy.org/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/cn.mrs"
  Telegram_域:
    <<: *Domain
    path: ./rules/Telegram.mrs
    url: "https://v6.gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/telegram.mrs"
  Telegram_IP:
    <<: *IPCIDR
    path: ./rules/Telegram_IP.mrs
    url: "https://v6.gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/telegram.mrs"
  AI_域:
    <<: *Domain
    path: ./rules/AI.mrs
    url: "https://v6.gh-proxy.org/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/ai.mrs"
  AI_IP:
    <<: *IPCIDR
    path: ./rules/AI_IP.mrs
    url: "https://v6.gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/ai.mrs"
  Private_域:
    <<: *Domain
    path: ./rules/LAN.mrs
    url: "https://v6.gh-proxy.org/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/private.mrs"
  Private_IP:
    <<: *IPCIDR
    path: ./rules/Private_IP.mrs
    url: "https://v6.gh-proxy.org/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/privateip.mrs"
  Games:
    <<: *Domain 
    path: ./rules/Games.mrs
    url: "https://v6.gh-proxy.org/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/games.mrs"
  GamesCN:
    <<: *Domain
    path: ./rules/GamesCN.mrs
    url: "https://v6.gh-proxy.org/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/games-cn.mrs"
  GameDownload:
    <<: *Domain
    path: ./rules/GameDownload.mrs
    url: "https://v6.gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-game-platforms-download.mrs"
  Blizzard:
    <<: *Domain
    path: ./rules/blizzard.mrs
    url: "https://v6.gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/blizzard.mrs"
  Ubisoft:
    <<: *Domain
    path: ./rules/ubisoft.mrs
    url: "https://v6.gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/ubisoft.mrs"
  Microsoft_域:
    <<: *Domain
    path: ./rules/Microsoft.mrs
    url: "https://v6.gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/microsoft.mrs"
  Nvidia_域:
    <<: *Domain
    path: ./rules/Nvidia.mrs
    url: "https://v6.gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/nvidia.mrs"

rules:
  - RULE-SET,Fake-IP-Filter,DIRECT
  - RULE-SET,Private_域,DIRECT
  - RULE-SET,Private_IP,DIRECT,no-resolve
  - RULE-SET,Directlist,DIRECT
  - RULE-SET,Applications,DIRECT
  - RULE-SET,GameDownload,DIRECT
  - RULE-SET,Nvidia_域,DIRECT
  - RULE-SET,Blizzard,DIRECT
  - RULE-SET,Ubisoft,DIRECT
  - RULE-SET,GamesCN,DIRECT
  - RULE-SET,Microsoft_域,DIRECT
  - RULE-SET,AI_域,AI
  - RULE-SET,AI_IP,AI,no-resolve
  - RULE-SET,Telegram_域,TG
  - RULE-SET,Telegram_IP,TG,no-resolve
  - RULE-SET,CN_域,DIRECT
  - RULE-SET,CN_IP,DIRECT,no-resolve
  - MATCH,Final
